### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by xzebra** [vidify/vidify#58]
It would be a great idea to integrate Docker into the project so you ensure it always runs in the same environment. It would also make the project easier to deploy.

**Comment by marioortizmanero** [comment]
Yes, very good idea. I've never used Docker, though, so I'm not sure how it would work out for the current usage. Docker is completely isolated, so there's no easy way to access the desktop's music player or record its audio.

For #29 it does seem interesting to easily deploy it to the devices mentioned at #56.

**Comment by marioortizmanero** [comment]
Closing this as in the end the External player works with a GUI too, and the Docker integration doesn't make much sense. Using a [virtual environment](https://docs.python.org/3/library/venv.html) is more appropriate because it still gives you access to the computer's PulseAudio devices, and works well with GUIs. Something more similar to Docker for GUIs is [Snap](https://snapcraft.io/), but I still haven't managed to make Vidify work on there.
