### ISSUE TITLE
Being able to un-mute the displayed videos

### ISSUE THREAD

**Issue by marioortizmanero** [vidify/vidify#66]
This would allow to mute spotify and let the youtube video play. That way, there's no need for audio synchronization. Some flag like `--with-audio` could be added in the config for this. Not sure if it's worth it, though.

**Comment by AndrewAmmerlaan** [comment]
Wouldn't this be problematic if the song on spotify and the song on youtube do not have the same length? If the song on youtube has a long intro, spotify would move to the next song before the youtube song is finished playing. Of course that could be fixed by using audiosync, but that would defeat the purpose of implementing the youtube audio in the first place, wouldn't it? 

Though it could work if vidify controls when the next song starts playing I guess. But then we would have a youtube player that is controlled by the spotify client. That would be kinda like an inverted vidify (I suppose that would be cool, we could name it yfidiv xD ). 

And sometimes the song on youtube is a completely different version of the same song (e.g. the one on youtube is live). 

I don't know, I suppose it could be done, but I think that using such a feature might create more problems then it fixes.

**Comment by marioortizmanero** [comment]
Yeah it's a feature that doesn't convince me much, I opened an issue to discuss it and see if it'd be worth it. It's definitely something that would have to be implemented after #77, which is already planned for the far future.

If the YouTube song is *larger* than the Spotify one, maybe it could be paused or just let it skip. After #77, if the YouTube song is *shorter* than the Spotify one, Vidify would just skip to the next one once it's finished. And if it's not even the same version of the song, there's not much that could be done...

I think it's best to revisit this in the future. It might not be that hard to implement. I'll just close this issue for now as the more I think about it, the worse the idea seems. I like the yfidiv name, though :laughing:
