### ISSUE TITLE
Consider forcing PySide2 rather than Qtpy

### ISSUE THREAD

**Issue by marioortizmanero** [vidify/vidify#84]
Honestly PyQt5 gives me nothing but problems. The packages always have installation issues and they don't even bother fixing them (see #49, it's the most visited page in this repo). Recently on Arch I'm having an issue where PyQtWebEngineWidgets won't work because it's missing even though it's actually installed. It also overcomplicates the installation unnecessarily.

@AndrewAmmerlaan you suggested using QtPy on #35, have you had any issues with PyQt5 whatsoever when packaging it for Gentoo? What's your opinion on this?

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan you suggested using QtPy on #35, have you had any issues with PyQt5 whatsoever when packaging it for Gentoo? What's your opinion on this?

I've not had any issues at all with PyQt5 (-5.14.1-r1) at the moment. In fact, my experience is quite the opposite, PyQt5 works fine, but PySide2 gives me problems. At the moment PySide2 is not in the main Gentoo repo (which doesn't complicate things that much cause vidify is not in the main repo and I could add PySide2 to ::guru), But I found that PySide2 didn't provide certain metadata (don't remember what it was exactly, but I think it had something to do with their `setup.py` file) which makes the `get_distribution(pyside2)` always fail (on gentoo) even if it is installed for some reason. Do you have similar problems on Arch?

My ebuild has support for the Vidify test suite (as all ebuilds *should* have), and I do always run it when version bumping the ebuild, just in case. I test it with PyQt5 (as I do not have PySide2 on my system at the moment), and I've never had it report any issues (other then the expected failures, because ebuilds do not have access to the internet by default).

Looking at the [Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/PyQt5/PyQt5-5.14.1-r1.ebuild) I do see some stuff that is clearly designed to fix things that are broken upstream, e.g:
```
		# Fix parallel install failure
		if python_is_python3; then
			sed -i -e '/INSTALLS += distinfo/i distinfo.depends = install_subtargets install_pep484_stubs install_qscintilla_api' \
				${PN}.pro || die
		else
			sed -i -e '/INSTALLS += distinfo/i distinfo.depends = install_subtargets install_qscintilla_api' \
				${PN}.pro || die
		fi
```

And there are more of such lines, so it definitely looks like, something is indeed broken with the PyQt5 installation process.
It might be that [Arch's pkgbuild](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/pyqt5) does not contain some of the fixes that the Gentoo ebuild does, which might explain why this works on Gentoo but gives problems on Arch. And maybe the other way around, is true for PySide2: the Arch pkgbuild might contain some fixes that are not (yet) in the Gentoo ebuild, which might cause the issues I found.

[SIDENOTE: This is why I sometimes wish Arch and Gentoo would be closer together, pkgbuilds and ebuilds are quite similar. Though ebuilds are definitely more advanced, support for binary repositories is still limited in Gentoo. But that's just me fantasizing about the ultimate distro that extends Gentoo's powerful portage, with Arch's excellent pre-compiled binaries and large repository.]

IMO, it would be a shame to force one of the two Qt4Python implementations just because distro X has packaging/compiling/installing/running issues with implementation Y. These implementations are functionally equivalent (this, and the fact that PyQt5 is considered more stable (don't know if that is actually true or not), is also one of the reasons why PySide2 is not in Gentoo). Apart from their respective installation issues, any app that works with one is more or less guaranteed to work with the other. 
That being said, it should be possible to switch the default implementation to PySide2, e.g.:
```
# If PyQt5 is installed and PySide2 is not, append PyQt5 to dependencies
if is_installed('PyQt5') and not is_installed('PySide2'):
    install_deps.append('PyQt5')
    install_deps.append('PyQtWebEngine>=5.14.0')  
# If PyQt5 is not installed, or if both PyQt5 and PySide2 are installed
# Use Pyside2, considered as default in Vidify
else:
    install_deps.append('PySide2')
```
Instead of:
```
# If PySide2 is installed and PyQt5 is not, append PySide2 to dependencies
if is_installed('PySide2') and not is_installed('PyQt5'):
    install_deps.append('PySide2')
# If PySide2 is not installed, or if both PyQt5 and PySide2 are installed
# Use QtPy's default: PyQt5
else:
    install_deps.append('PyQt5')
    install_deps.append('PyQtWebEngine>=5.14.0')
```
But I'm not sure if that will fix anything, it just shifts the default, and doesn't address the root cause of the installation issues with PyQt5/PySide2.

**Comment by marioortizmanero** [comment]
Turns out the issue on Arch Linux was due to an incorrect installation of `PyQt5`, since the `pip` and `pacman` installations were colliding.

Thanks for sharing your experience Andrew. I'll just leave this as it is. I also wish Arch and Gentoo were more close together, but in the end I think their philosophies are quite different, so I'm not sure how that would work out. But yeah, fragmentation on Linux has always been a problem :/
